#define AMBIENT_MUSIC_CHANNEL				707
#define AMBIENT_ENVIRONMENT_CHANNEL			708
#define AMBIENT_BACKGROUND_CHANNEL			708
#define AMBIENT_PSY_CHANNEL					710
#define TURNTABLE_CHANNEL					711
#define AMBIENT_CAMPFIRE_CHANNEL			712